const months=[['MONTH 1','👶 Hello, world'],['MONTH 2','😊 First smile'],['MONTH 3','🤲 Found her hands'],['MONTH 4','😂 First giggle'],['MONTH 5','🔄 Rolled over'],['MONTH 6','🍚 Annaprashan'],['MONTH 7','🪑 Sat up tall'],['MONTH 8','🦷 First tooth'],['MONTH 9','🐢 Crawling'],['MONTH 10','👋 Bye-bye wave'],['MONTH 11','🗣️ Said “Mama”'],['MONTH 12','👣 First steps']];
const plan=[['🎈 4:00 PM','Welcome & balloons','Grab a balloon, a juice box and a spot on the play mats.'],['🎩 4:30 PM','Magic show','Uncle Jimmy’s bubbles and rabbits — suitable for all ages.'],['🎂 5:15 PM','Cake cutting','Aarya’s first taste of cake. Cameras ready — it will get messy.'],['🍕 5:45 PM','Snacks & dinner','Mini pizzas, pav bhaji and a kids’ menu the adults will steal.'],['🎁 6:30 PM','Return gifts','A little thank-you bag for every little guest.']];
const corners=[['🫧','Bubble zone','A bubble machine that runs all afternoon.'],['🎨','Tattoo & face paint','Butterflies, tigers and glitter for the brave.'],['📸','Photo booth','Props, a balloon wall and prints to take home.'],['🧸','Soft play','A padded corner for the crawlers and toddlers.']];
document.querySelector('#months').innerHTML=months.map(([m,t])=>`<div><span>${m}</span><strong>${t}</strong></div>`).join('');
document.querySelector('#planList').innerHTML=plan.map(([time,title,copy])=>`<article class="plan-item"><b>${time}</b><div><h3>${title}</h3><p>${copy}</p></div></article>`).join('');
document.querySelector('#cornerGrid').innerHTML=corners.map(([icon,title,copy])=>`<article class="corner"><div class="icon">${icon}</div><h3>${title}</h3><p>${copy}</p></article>`).join('');
const gate=document.querySelector('#gate'),party=document.querySelector('#party'),gateBalloons=document.querySelector('#gateBalloons');
const colors=['#e99aba','#f4cf64','#82b3ef','#aa98ed','#9bd9c2','#f2ae7b']; let popped=0;
colors.forEach((color,i)=>{const b=document.createElement('button');b.className='pop-balloon';b.setAttribute('aria-label','Pop balloon');b.style.cssText=`background:${color};left:${12+i*14}%;top:${12+(i%3)*24}%;transform:rotate(${i%2?8:-8}deg)`;b.onclick=()=>{if(b.classList.contains('popped'))return;b.classList.add('popped');popped++;if(popped===colors.length)openParty()};gateBalloons.appendChild(b)});
function openParty(){gate.classList.add('hidden');party.classList.add('open');party.setAttribute('aria-hidden','false');document.body.style.overflow='auto'}
document.querySelector('#skipGate').onclick=openParty;document.body.style.overflow='hidden';
const target=new Date('2026-11-22T16:00:00+05:30');function updateTimer(){let d=Math.max(0,target-new Date()),s=Math.floor(d/1000),days=Math.floor(s/86400);s%=86400;const hours=Math.floor(s/3600);s%=3600;const mins=Math.floor(s/60);s%=60;document.querySelector('#timer').textContent=`${days} DAYS ${String(hours).padStart(2,'0')} HOURS ${String(mins).padStart(2,'0')} MINUTES ${String(s).padStart(2,'0')} SECONDS`}updateTimer();setInterval(updateTimer,1000);
function reveal(){document.querySelector('#scratchButton').classList.add('revealed');document.querySelector('#scratchButton small').textContent='DATE REVEALED'}document.querySelector('#scratchButton').onclick=reveal;document.querySelector('#revealButton').onclick=reveal;
document.querySelector('#wishForm').addEventListener('submit',e=>{e.preventDefault();const text=document.querySelector('#wishText').value.trim(),name=document.querySelector('#wishName').value.trim();if(!text||!name)return;const item=document.createElement('div');item.innerHTML=`${text}<small>${name}</small>`;document.querySelector('#wishWall').append(item);e.target.reset()});
document.querySelector('#map').onclick=e=>{e.currentTarget.textContent='Map ready — use “Get directions” below';e.currentTarget.style.background='linear-gradient(135deg,#a8d8ed,#c9e9ba)'};
document.querySelector('#rsvpForm').addEventListener('submit',e=>{e.preventDefault();document.querySelector('#rsvpNote').textContent='Thanks — your RSVP has been noted! 🎈';e.target.reset()});
document.querySelector('#calendarButton').onclick=()=>{const ics=['BEGIN:VCALENDAR','VERSION:2.0','BEGIN:VEVENT','DTSTART:20261122T103000Z','DTEND:20261122T133000Z','SUMMARY:Aarya’s 1st Birthday Party','LOCATION:The Little Garden Café, Gurugram','END:VEVENT','END:VCALENDAR'].join('\\n');const blob=new Blob([ics],{type:'text/calendar'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='aarya-birthday.ics';a.click();URL.revokeObjectURL(url)};
let audioCtx;document.querySelector('#musicButton').onclick=()=>{if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=523.25;g.gain.value=.03;o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.25);document.querySelector('#musicButton').textContent='♪ Music'};
document.querySelector('#shareButton').onclick=async()=>{if(navigator.share)await navigator.share({title:'Aarya turns One!',text:'Come celebrate Aarya’s first birthday!',url:location.href});else{await navigator.clipboard.writeText(location.href);alert('Invitation link copied!')}};
